/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * API version: 3.04.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EliminationAllianceStatus struct {
	PlayoffAverage float64 `json:"playoff_average,omitempty"`
	Level string `json:"level,omitempty"`
	Record WltRecord `json:"record,omitempty"`
	CurrentLevelRecord WltRecord `json:"current_level_record,omitempty"`
	Status string `json:"status,omitempty"`
}
