/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * API version: 3.04.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A Win-Loss-Tie record for a team, or an alliance.
type WltRecord struct {

	// Number of losses.
	Losses int32 `json:"losses"`

	// Number of wins.
	Wins int32 `json:"wins"`

	// Number of ties.
	Ties int32 `json:"ties"`
}
